<script setup>
import { reactive, ref } from 'vue'
import { onLoad, onPullDownRefresh, onReachBottom } from '@dcloudio/uni-app'
import { getActivities, getMyActivities } from '@/api/campus'
const tab=ref('all'),list=ref([]),total=ref(0),page=ref(0),loading=ref(false);const query=reactive({category:'',status:''})
async function load(reset=false){if(tab.value==='mine'){if(!uni.getStorageSync('token'))return uni.navigateTo({url:'/pages/auth/index'});list.value=await getMyActivities();total.value=list.value.length;return}if(loading.value||(!reset&&page.value&&list.value.length>=total.value))return;loading.value=true;try{const next=reset?1:page.value+1;const data=await getActivities({...query,page:next,size:10});const items=Array.isArray(data?.list)?data.list:[];list.value=reset?items:list.value.concat(items);total.value=Number(data?.total)||0;page.value=next}finally{loading.value=false}}
function select(value){tab.value=value;page.value=0;list.value=[];load(true)}
onLoad(()=>load(true));onPullDownRefresh(async()=>{try{await load(true)}finally{uni.stopPullDownRefresh()}});onReachBottom(()=>load())
</script>
<template><view class="screen"><view class="tabs"><view class="tab" :class="{active:tab==='all'}" @click="select('all')">全部活动</view><view class="tab" :class="{active:tab==='mine'}" @click="select('mine')">我的活动</view></view><view v-if="tab==='all'" class="panel row filters"><picker :range="['全部分类','体育','文艺','学术','志愿']" @change="query.category=['','SPORTS','CULTURE','ACADEMIC','VOLUNTEER'][$event.detail.value]"><view class="field picker">{{ {'':'全部分类',SPORTS:'体育',CULTURE:'文艺',ACADEMIC:'学术',VOLUNTEER:'志愿'}[query.category] }}</view></picker><picker :range="['全部状态','即将开始','进行中','已结束']" @change="query.status=['','UPCOMING','ONGOING','ENDED'][$event.detail.value]"><view class="field picker">{{ {'':'全部状态',UPCOMING:'即将开始',ONGOING:'进行中',ENDED:'已结束'}[query.status] }}</view></picker><button class="primary-btn" @click="load(true)">筛选</button></view><view v-for="item in list" :key="item.id" class="activity" @click="uni.navigateTo({url:`/pages/detail/index?type=activity&id=${item.id}`})"><image v-if="item.coverImage" class="activity-image" :src="item.coverImage" mode="aspectFill"/><view class="activity-main"><view class="activity-top"><text class="status">{{ item.status }}</text><text>{{ item.category }}</text></view><view class="item-title">{{ item.title }}</view><view class="item-meta"><text>{{ item.location }}</text><text>{{ item.startTime }}</text><text>{{ item.currentParticipants }}/{{ item.maxParticipants }} 人</text></view></view></view><view v-if="!list.length&&!loading" class="empty-state">暂无活动</view></view></template>
<style scoped lang="scss">.filters{align-items:flex-start}.filters picker{flex:1;min-width:0}.filters .field{margin:0;padding:0 12rpx;line-height:76rpx}.filters .primary-btn{flex:0 0 120rpx}.activity{margin-bottom:18rpx;overflow:hidden;border:1rpx solid #ece4fb;border-radius:22rpx;background:#fff;box-shadow:0 8rpx 26rpx rgba(124,92,214,.07)}.activity-image{display:block;width:100%;height:260rpx}.activity-main{padding:24rpx}.activity-top{display:flex;justify-content:space-between;margin-bottom:12rpx;color:$campus-text-muted;font-size:23rpx}.status{color:$campus-brand}</style>
