<script setup>
import { computed, reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { cancelActivity, checkinActivity, createProductOrder, evaluateRepair, favoriteProduct, getActivityDetail, getLocationDetail, getNoticeDetail, getProductDetail, getRepairDetail, readNotice, registerActivity } from '@/api/campus'
const item=ref(null),type=ref(''),id=ref('');const form=reactive({message:'',remark:'',code:'',score:5,content:''})
const loaders={notice:getNoticeDetail,repair:getRepairDetail,product:getProductDetail,activity:getActivityDetail,location:getLocationDetail}
const labels={location:'地点',address:'地址',building:'楼栋',room:'房间',contactPhone:'联系电话',wechat:'微信',startTime:'开始时间',endTime:'结束时间',maxParticipants:'人数上限',currentParticipants:'已报名',expectedTime:'预计处理',statusDesc:'处理进度'}
const title=computed(()=>item.value?.title||item.value?.name||'详情')
async function requireAction(fn){if(!uni.getStorageSync('token'))return uni.navigateTo({url:'/pages/auth/index'});await fn();uni.showToast({title:'操作成功'})}
async function action(name){if(name==='read')await requireAction(()=>readNotice(id.value));if(name==='evaluate')await requireAction(()=>evaluateRepair({repairId:Number(id.value),score:Number(form.score),content:form.content}));if(name==='favorite')await requireAction(()=>favoriteProduct(id.value));if(name==='order')await requireAction(()=>createProductOrder({productId:Number(id.value),message:form.message}));if(name==='register')await requireAction(()=>registerActivity({activityId:Number(id.value),remark:form.remark}));if(name==='cancel')await requireAction(()=>cancelActivity(id.value));if(name==='checkin')await requireAction(()=>checkinActivity({activityId:Number(id.value),code:form.code}))}
function openLocation(){uni.openLocation({longitude:Number(item.value.longitude),latitude:Number(item.value.latitude),name:item.value.name,address:item.value.address})}
onLoad(async options=>{type.value=options.type;id.value=options.id;if(type.value==='repair'&&!uni.getStorageSync('token'))return uni.redirectTo({url:'/pages/auth/index'});const loader=loaders[type.value];if(!loader)return;item.value=await loader(id.value);uni.setNavigationBarTitle({title:title.value});if(type.value==='notice'&&uni.getStorageSync('token'))readNotice(id.value).catch(()=>{})})
</script>
<template><view v-if="item" class="screen"><image v-if="item.coverImage||item.image" class="hero" :src="item.coverImage||item.image" mode="aspectFill"/><view class="panel detail"><view class="title">{{ title }}</view><view class="item-meta"><text>{{ item.category||item.type }}</text><text>{{ item.status }}</text><text>{{ item.author||item.department }}</text><text>{{ item.createTime||item.startTime }}</text></view><view v-if="item.price!==undefined" class="price">¥{{ item.price }}</view><rich-text v-if="item.content" class="content" :nodes="item.content"/><view v-if="item.description" class="content">{{ item.description }}</view><view class="facts"><view v-for="key in ['location','address','building','room','contactPhone','wechat','startTime','endTime','maxParticipants','currentParticipants','expectedTime','statusDesc']" v-show="item[key]!==undefined" :key="key" class="fact"><text class="muted">{{ labels[key] }}</text><text>{{ item[key] }}</text></view></view></view><view v-if="type==='notice'" class="panel"><button class="primary-btn" @click="action('read')">标记已读</button></view><view v-if="type==='repair'" class="panel"><view class="section-title">评价维修</view><slider :value="form.score" min="1" max="5" show-value active-color="#7c5cd6" @change="form.score=$event.detail.value"/><textarea v-model="form.content" class="textarea" placeholder="评价内容"/><button class="primary-btn" @click="action('evaluate')">提交评价</button></view><view v-if="type==='product'" class="panel"><input v-model="form.message" class="field" placeholder="给卖家留言"/><view class="row"><button class="secondary-btn" @click="action('favorite')">收藏</button><button class="primary-btn" @click="action('order')">创建订单</button></view></view><view v-if="type==='activity'" class="panel"><input v-model="form.remark" class="field" placeholder="报名备注"/><view class="row"><button class="primary-btn" @click="action('register')">报名</button><button class="danger-btn" @click="action('cancel')">取消报名</button></view><input v-model="form.code" class="field checkin" placeholder="签到码"/><button class="secondary-btn" @click="action('checkin')">活动签到</button></view><view v-if="type==='location'" class="panel"><button class="primary-btn" @click="openLocation">在地图中打开</button></view></view><view v-else class="empty-state">加载中...</view></template>
<style scoped lang="scss">.hero{width:100%;height:360rpx;border-radius:22rpx}.detail{margin-top:20rpx}.title{font-size:40rpx;font-weight:700;line-height:1.45}.price{margin:22rpx 0;color:#f56c6c;font-size:44rpx;font-weight:700}.content{display:block;margin-top:28rpx;line-height:1.8;white-space:pre-wrap}.facts{margin-top:24rpx}.fact{display:flex;justify-content:space-between;padding:14rpx 0;border-bottom:1rpx solid #ebeef5;gap:24rpx}.checkin{margin-top:18rpx}</style>
