<script setup>
import { nextTick, reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { chat, getHotQuestions, getProcess, getRecommendations } from '@/api/campus'
const messages=ref([]),question=ref(''),hot=ref([]),busy=ref(false),viewId=ref('');const processForm=reactive({type:'LIBRARY',action:''});const recommendations=ref([])
async function ask(text=question.value){if(!text.trim())return;if(!uni.getStorageSync('token'))return uni.navigateTo({url:'/pages/auth/index'});messages.value.push({role:'user',content:text});question.value='';busy.value=true;try{const data=await chat({question:text,history:messages.value.slice(0,-1)});messages.value.push({role:'assistant',content:data.answer});(data.relatedQuestions||[]).forEach(content=>hot.value.push({question:content}))}finally{busy.value=false;await nextTick();viewId.value=`m${messages.value.length-1}`}}
async function process(){const data=await getProcess(processForm);messages.value.push({role:'assistant',content:data.answer||data.content||data.steps?.join('\n')||'已查到办事流程'})}
async function recommend(type){if(!uni.getStorageSync('token'))return uni.navigateTo({url:'/pages/auth/index'});recommendations.value=await getRecommendations(type)}
onLoad(async()=>{hot.value=await getHotQuestions()})
</script>
<template><view class="ai-page"><scroll-view scroll-y class="conversation" :scroll-into-view="viewId"><view class="welcome"><view class="welcome-shine"/><view class="ai-mark">AI</view><view class="welcome-copy"><view class="welcome-label">CAMPUS ASSISTANT</view><view class="welcome-title">校园智慧助手</view><view class="welcome-sub">课程、校园卡、宿舍与考试，随时问我</view></view></view><view v-for="(item,index) in messages" :id="`m${index}`" :key="index" class="message" :class="item.role"><text>{{ item.content }}</text></view><view v-if="busy" class="message assistant"><text class="thinking-dot">正在思考...</text></view><view v-if="!messages.length" class="hot"><view class="hot-title">猜你想问</view><view class="question-list"><text v-for="item in hot" :key="item.id||item.question" class="question" @click="ask(item.question||item.content)">{{ item.question||item.content }} ›</text></view></view><view class="tools panel"><view class="section-title">办事助手</view><view class="tool-hint">选择业务类型，快速查询办理流程</view><picker :range="['图书馆','校园卡','宿舍','考试']" @change="processForm.type=['LIBRARY','CARD','DORMITORY','EXAM'][$event.detail.value]"><view class="field picker">{{ {LIBRARY:'图书馆',CARD:'校园卡',DORMITORY:'宿舍',EXAM:'考试'}[processForm.type] }}<text>⌄</text></view></picker><input v-model="processForm.action" class="field" placeholder="要办理的事项"/><button class="secondary-btn" @click="process">查询办理流程</button><view class="recommend-title">个性推荐</view><view class="row recommend"><button class="secondary-btn" @click="recommend('COURSE')">课程</button><button class="secondary-btn" @click="recommend('ACTIVITY')">活动</button><button class="secondary-btn" @click="recommend('CANTEEN')">食堂</button></view><view v-for="(item,index) in recommendations" :key="index" class="recommendation">{{ item.title||item.name||item.content }}</view></view></scroll-view><view class="composer"><input v-model="question" class="input" placeholder="问问校园助手..." confirm-type="send" @confirm="ask()"/><button class="send" :disabled="busy" @click="ask()">发送</button></view></view></template>
<style scoped lang="scss">
.ai-page{height:100vh;background:linear-gradient(180deg,#f6f2fd,#fbf6fb 70%,#fff8f4)}
.conversation{height:calc(100vh - 124rpx);padding:24rpx;box-sizing:border-box}
.welcome{position:relative;display:flex;align-items:center;gap:20rpx;margin-bottom:28rpx;padding:30rpx;overflow:hidden;border-radius:24rpx;background:linear-gradient(135deg,#241457,#7c5cd6 68%,#b06fd0);color:#fff;box-shadow:0 14rpx 36rpx rgba(36,20,87,.2)}
.welcome-shine{position:absolute;right:-70rpx;bottom:-120rpx;width:260rpx;height:260rpx;border-radius:50%;background:rgba(255,255,255,.1)}
.ai-mark{position:relative;display:flex;align-items:center;justify-content:center;width:80rpx;height:80rpx;border:1rpx solid rgba(255,255,255,.42);border-radius:22rpx;background:rgba(255,255,255,.14);color:#fff;font-size:27rpx;font-weight:800}
.welcome-copy{position:relative;flex:1}.welcome-label{color:#ffe9ad;font-size:18rpx;font-weight:700;letter-spacing:2rpx}.welcome-title{margin-top:4rpx;font-size:32rpx;font-weight:700}.welcome-sub{margin-top:6rpx;color:rgba(255,255,255,.7);font-size:21rpx}
.message{max-width:82%;margin-bottom:18rpx;padding:20rpx 24rpx;border-radius:20rpx;line-height:1.65;white-space:pre-wrap;box-shadow:0 7rpx 20rpx rgba(79,54,145,.06)}.assistant{margin-right:auto;border:1rpx solid #ece4fb;background:#fff}.user{margin-left:auto;background:linear-gradient(120deg,#7c5cd6,#9568d4);color:#fff}.thinking-dot{color:#8f82af}
.hot{margin-bottom:26rpx}.hot-title{margin-bottom:14rpx;color:$campus-text-main;font-weight:700}.question-list{display:flex;flex-direction:column;gap:12rpx}.question{padding:18rpx 20rpx;border:1rpx solid #e4dbf6;border-radius:18rpx;background:rgba(255,255,255,.92);color:#6247ab;box-shadow:0 6rpx 18rpx rgba(79,54,145,.05)}
.tools{margin-bottom:24rpx}.tools .section-title{margin-bottom:4rpx}.tool-hint{margin-bottom:22rpx;color:$campus-text-muted;font-size:22rpx}.picker{display:flex;align-items:center;justify-content:space-between;line-height:84rpx}.recommend-title{margin-top:26rpx;color:$campus-text-main;font-weight:700}.recommend{margin-top:14rpx}.recommendation{padding:16rpx 0;border-bottom:1rpx solid #ebeef5}
.composer{display:flex;height:124rpx;padding:18rpx 24rpx 24rpx;border-top:1rpx solid #ece4fb;background:rgba(255,255,255,.96);gap:14rpx;box-shadow:0 -8rpx 28rpx rgba(79,54,145,.07)}.input{flex:1;height:82rpx;padding:0 24rpx;border:1rpx solid #ddd3f3;border-radius:20rpx;background:#faf8ff}.send{width:132rpx;height:82rpx;margin:0;border:0;border-radius:20rpx;background:linear-gradient(120deg,#7c5cd6,#b06fd0);color:#fff;font-size:27rpx;font-weight:600;line-height:82rpx}.send::after{border:0}
</style>
