<script setup>
import { reactive, ref } from 'vue'
import { onLoad, onPullDownRefresh, onReachBottom } from '@dcloudio/uni-app'
import { getProducts, publishProduct } from '@/api/campus'
const tab=ref('list'),list=ref([]),total=ref(0),page=ref(0),loading=ref(false)
const query=reactive({keyword:'',categoryId:'',minPrice:'',maxPrice:'',status:0})
const form=reactive({title:'',price:'',description:'',categoryId:'',images:'',contactPhone:'',wechat:''})
async function load(reset=false){if(loading.value||(!reset&&page.value&&list.value.length>=total.value))return;loading.value=true;try{const next=reset?1:page.value+1;const data=await getProducts({...query,page:next,size:10});const items=Array.isArray(data?.list)?data.list:[];list.value=reset?items:list.value.concat(items);total.value=Number(data?.total)||0;page.value=next}finally{loading.value=false}}
async function publish(){if(!uni.getStorageSync('token'))return uni.navigateTo({url:'/pages/auth/index'});await publishProduct({...form,price:Number(form.price),categoryId:Number(form.categoryId),images:form.images.split(',').map(v=>v.trim()).filter(Boolean)});uni.showToast({title:'发布成功'});tab.value='list';load(true)}
onLoad(()=>load(true));onPullDownRefresh(async()=>{try{await load(true)}finally{uni.stopPullDownRefresh()}});onReachBottom(()=>load())
</script>
<template><view class="screen"><view class="tabs"><view class="tab" :class="{active:tab==='list'}" @click="tab='list'">逛市场</view><view class="tab" :class="{active:tab==='publish'}" @click="tab='publish'">发布商品</view></view><template v-if="tab==='list'"><view class="panel filter"><view class="filter-title">筛选商品</view><input v-model="query.keyword" class="field search-field" placeholder="搜索商品名称" confirm-type="search" @confirm="load(true)"/><view class="price-filter"><input v-model="query.minPrice" class="field" type="digit" placeholder="最低价"/><text class="price-divider">—</text><input v-model="query.maxPrice" class="field" type="digit" placeholder="最高价"/></view><button class="primary-btn filter-btn" @click="load(true)">应用筛选</button></view><view class="result-head"><text>为你找到 {{ total }} 件商品</text><text class="result-hint">下拉可刷新</text></view><view v-for="item in list" :key="item.id" class="product" @click="uni.navigateTo({url:`/pages/detail/index?type=product&id=${item.id}`})"><image v-if="item.coverImage" class="product-image" :src="item.coverImage" mode="aspectFill"/><view v-else class="product-image placeholder">闲置</view><view class="product-copy"><view class="item-title">{{ item.title }}</view><view class="price">¥{{ item.price }}</view><view class="item-meta"><text>{{ item.category }}</text><text>{{ item.status }}</text><text>{{ item.viewCount||0 }} 浏览</text></view></view></view><view v-if="!list.length&&!loading" class="empty-state">暂无商品</view></template><view v-else class="panel"><view class="section-title">发布闲置商品</view><input v-model="form.title" class="field" placeholder="商品标题"/><input v-model="form.price" class="field" type="digit" placeholder="价格"/><input v-model="form.categoryId" class="field" type="number" placeholder="分类 ID"/><textarea v-model="form.description" class="textarea" placeholder="商品描述"/><input v-model="form.images" class="field" placeholder="图片 URL，多个逗号分隔"/><input v-model="form.contactPhone" class="field" type="number" placeholder="联系电话"/><input v-model="form.wechat" class="field" placeholder="微信号（可选）"/><button class="primary-btn" @click="publish">发布商品</button></view></view></template>
<style scoped lang="scss">.filter-title{margin-bottom:18rpx;color:$campus-text-main;font-size:30rpx;font-weight:700}.filter .field{margin-bottom:16rpx}.search-field{background:#fff}.price-filter{display:grid;grid-template-columns:minmax(0,1fr) 32rpx minmax(0,1fr);align-items:center;margin-bottom:18rpx}.price-filter .field{min-width:0;margin:0}.price-divider{color:$campus-text-muted;text-align:center}.filter-btn{width:100%;margin:0}.result-head{display:flex;justify-content:space-between;margin:4rpx 4rpx 18rpx;color:$campus-text-secondary;font-size:23rpx}.result-hint{color:$campus-text-muted}.product{display:flex;gap:20rpx;margin-bottom:18rpx;padding:20rpx;border:1rpx solid #ece4fb;border-radius:22rpx;background:#fff;box-shadow:0 8rpx 26rpx rgba(124,92,214,.07)}.product-image{flex:0 0 190rpx;width:190rpx;height:160rpx;border-radius:14rpx}.placeholder{display:flex;align-items:center;justify-content:center;background:#efe9fc;color:#694ab9}.product-copy{display:flex;flex:1;min-width:0;flex-direction:column}.price{margin-top:16rpx;color:#f56c6c;font-size:35rpx;font-weight:700}.product-copy .item-meta{margin-top:auto}</style>
