<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getLocations, getRoute, searchLocations } from '@/api/campus'
const locations=ref([]),keyword=ref(''),category=ref(''),selected=ref(null),route=ref(null)
const markers=computed(()=>locations.value.map(item=>({id:Number(item.id),longitude:Number(item.longitude),latitude:Number(item.latitude),title:item.name,width:28,height:34})))
const center=computed(()=>selected.value||locations.value[0]||{longitude:103.9979,latitude:30.7576})
async function load(){locations.value=await getLocations({category:category.value});selected.value=locations.value[0]||null}
async function search(){locations.value=keyword.value.trim()?await searchLocations(keyword.value.trim()):await getLocations({category:category.value});selected.value=locations.value[0]||null}
function marker(e){selected.value=locations.value.find(v=>Number(v.id)===Number(e.detail.markerId))||null}
function navigate(){if(!selected.value)return;uni.getLocation({type:'gcj02',success:async pos=>{route.value=await getRoute({fromLng:pos.longitude,fromLat:pos.latitude,toLng:selected.value.longitude,toLat:selected.value.latitude,mode:'walk'})},fail:()=>uni.showToast({title:'请允许定位权限',icon:'none'})})}
function detail(){if(selected.value)uni.navigateTo({url:`/pages/detail/index?type=location&id=${selected.value.id}`})}
onLoad(load)
</script>
<template><view class="map-page"><map class="map" :longitude="Number(center.longitude)" :latitude="Number(center.latitude)" :markers="markers" show-location @markertap="marker"/><view class="sheet"><view class="search row"><input v-model="keyword" class="field" placeholder="搜索地点" confirm-type="search" @confirm="search"/><button class="primary-btn" @click="search">搜索</button></view><scroll-view scroll-x class="categories"><view class="category-row"><text v-for="item in [['','全部'],['BUILDING','教学楼'],['LIBRARY','图书馆'],['CANTEEN','食堂'],['DORMITORY','宿舍'],['GYM','体育馆']]" :key="item[0]" class="chip" :class="{active:category===item[0]}" @click="category=item[0];load()">{{ item[1] }}</text></view></scroll-view><view v-if="selected" class="place"><view @click="detail"><view class="item-title">{{ selected.name }}</view><view class="muted">{{ selected.address }}</view></view><button class="secondary-btn route-btn" @click="navigate">步行路线</button></view><scroll-view v-if="route" scroll-y class="route"><view class="route-head">{{ route.distance }} 米 · 约 {{ route.duration }} 分钟</view><view v-for="(step,index) in route.steps" :key="index" class="step">{{ index+1 }}. {{ step.instruction }}</view></scroll-view></view></view></template>
<style scoped lang="scss">.map-page{position:relative;height:100vh}.map{width:100%;height:52vh}.sheet{height:48vh;padding:20rpx 24rpx;background:#fff}.search{align-items:flex-start}.search .field{flex:1}.search .primary-btn{flex:0 0 120rpx}.categories{white-space:nowrap}.category-row{display:inline-flex;gap:10rpx}.chip{padding:10rpx 18rpx;border:1rpx solid #dcd2f7;border-radius:999rpx}.chip.active{border-color:$campus-brand;background:$campus-brand;color:#fff}.place{display:flex;align-items:center;justify-content:space-between;margin-top:18rpx;padding-top:18rpx;border-top:1rpx solid #ebeef5}.place>view{flex:1;min-width:0}.route-btn{width:160rpx;margin-left:16rpx}.route{max-height:180rpx;margin-top:16rpx}.route-head{font-weight:700}.step{padding:8rpx 0;color:$campus-text-secondary}</style>
